#
# hr 系統相關設定
#

Callback_Path: /login_callback

OAuth_Service:
 Authorize: https://auth.ischool.com.tw/oauth/authorize.php
 Logout: https://auth.ischool.com.tw/logout.php
 Token: https://auth.ischool.com.tw/oauth/token.php
 Me: https://auth.ischool.com.tw/services/me.php

GAPI_ClientID: 291795125064-b2dfrq97tt6prpiimfsl19rk8fk5743r.apps.googleusercontent.com
GAPI_ClientSecret: jmTHciqnQpr69myHUZxCaH-g